name: Auto merge & push
on:
  pull_request:
    types: [opened, synchronize]   # PR 更新时触发
jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: 等待 CI 全部通过
        uses: lewagon/wait-on-check-action@v1.3.1   # 可选：等 CI
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-name: 'merge'               # 改成你的 CI job 名
          wait-interval: 30
      - name: 自动合并
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash                       # 可选：merge / squash / rebase
