# .github/workflows/auto-merge-pr.yml
name: Auto-merge PR

on:
  # 每次 PR 状态更新（新 commit、CI 完成、review 提交等）
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
  # 当外部检查完成（CI 成功/失败）
  check_suite:
    types: [completed]

permissions:
  contents: write        # 合并 PR 需要写权限
  pull-requests: write   # 打标签、评论、删除分支

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      # 1. 检查 PR 是否满足自动合并条件
      - name: Auto-merge if labeled and ready
        uses: pascalgn/merge-action@v0.16.3
        with:
          # 仅当 PR 带有指定标签时自动合并
          labels: auto-merge
          # 合并策略：squash / merge / rebase
          merge-method: squash
          # 合并后自动删除源分支
          delete-branch: true
          # PR 标题作为提交信息
          squash-title: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
