# .github/workflows/auto-merge.yml
name: Auto-merge PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge
        uses: pascalgn/automerge-action@v0.16.3   # ✅ 正确的仓库与版本
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "automerge"               # 当 PR 打上该标签时才会合并
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: "pull-request-title"
